import type { RefundCase } from "@shared/schema";
import { calculateRiskScore } from "./scoringEngine";

function makeCase(partial: Omit<RefundCase, "riskAssessment" | "status" | "auditTrail"> & { status?: RefundCase["status"]; auditTrail?: RefundCase["auditTrail"] }): RefundCase {
  const base: RefundCase = {
    ...partial,
    auditTrail: partial.auditTrail || [],
    status: partial.status || "pending",
  };
  const assessment = calculateRiskScore(base);

  let status: RefundCase["status"] = base.status;
  if (status === "pending") {
    if (assessment.category === "auto_approve") status = "auto_approved";
    else if (assessment.category === "medium_risk") status = "medium_risk";
    else status = "high_risk";
  }

  const now = new Date();
  const auditTrail = [
    {
      id: `audit-${base.id}-1`,
      caseId: base.id,
      timestamp: new Date(now.getTime() - 60 * 60 * 1000 * 3).toISOString(),
      action: "Case Received",
      actor: "system" as const,
      detail: "Refund request submitted by customer.",
    },
    {
      id: `audit-${base.id}-2`,
      caseId: base.id,
      timestamp: new Date(now.getTime() - 60 * 60 * 1000 * 2.9).toISOString(),
      action: "Risk Assessment",
      actor: "system" as const,
      detail: `Risk score calculated: ${assessment.totalScore} pts — ${assessment.systemDecision}`,
    },
  ];

  return {
    ...base,
    status,
    riskAssessment: assessment,
    auditTrail,
  };
}

export const MOCK_CASES: RefundCase[] = [
  makeCase({
    id: "RC-001",
    customerId: "CUST-4421",
    customerName: "Marcus Chen",
    customerEmail: "marcus.chen@email.com",
    bookingId: "BK-887234",
    experienceName: "Michelin Star Tasting Menu — Le Bernadin",
    experienceCategory: "Dining",
    experienceValue: 420,
    experienceValuePercentile: 96,
    refundReason: "no_show",
    refundAmount: 420,
    refundTimingHours: -2,
    customerTenureMonths: 8,
    refundCountLast6Months: 22,
    totalRefundCount: 28,
    emailEngagement: "opened",
    systemLoginsLast24h: 1,
    previousNoShowCount: 5,
    requestDate: "2026-03-02T09:15:00Z",
    experienceDate: "2026-03-01T19:00:00Z",
    emailEngagementLog: [
      { timestamp: "2026-03-01T17:02:00Z", event: "Email Opened", device: "iPhone 15", location: "New York, NY" },
      { timestamp: "2026-03-01T17:05:00Z", event: "Booking Link Clicked", device: "iPhone 15", location: "New York, NY" },
    ],
    refundHistory: [
      { date: "2026-02-15", experience: "Broadway Show — Hamilton", amount: 180, reason: "No Show", outcome: "Approved" },
      { date: "2026-01-28", experience: "Helicopter Tour NYC", amount: 320, reason: "No Show", outcome: "Approved" },
      { date: "2026-01-10", experience: "Museum of Natural History VIP", amount: 95, reason: "Technical Issue", outcome: "Approved" },
      { date: "2025-12-22", experience: "New Year's Eve Gala", amount: 550, reason: "No Show", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-002",
    customerId: "CUST-7718",
    customerName: "Priya Sharma",
    customerEmail: "priya.sharma@gmail.com",
    bookingId: "BK-991102",
    experienceName: "Sunset Sailing — New York Harbor",
    experienceCategory: "Outdoor",
    experienceValue: 89,
    experienceValuePercentile: 45,
    refundReason: "cancellation",
    refundAmount: 89,
    refundTimingHours: 72,
    customerTenureMonths: 36,
    refundCountLast6Months: 1,
    totalRefundCount: 2,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-01T14:22:00Z",
    experienceDate: "2026-03-04T17:00:00Z",
    refundHistory: [
      { date: "2025-05-10", experience: "Comedy Night at the Cellar", amount: 45, reason: "Family Emergency", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-003",
    customerId: "CUST-2259",
    customerName: "Tyler Brooks",
    customerEmail: "tbrooks99@outlook.com",
    bookingId: "BK-334556",
    experienceName: "Helicopter Tour — Grand Canyon",
    experienceCategory: "Adventure",
    experienceValue: 580,
    experienceValuePercentile: 98,
    refundReason: "cancellation",
    refundAmount: 580,
    refundTimingHours: 4.5,
    customerTenureMonths: 14,
    refundCountLast6Months: 7,
    totalRefundCount: 9,
    emailEngagement: "opened",
    systemLoginsLast24h: 2,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T08:30:00Z",
    experienceDate: "2026-03-02T13:00:00Z",
    refundHistory: [
      { date: "2026-02-01", experience: "Scuba Diving Keys", amount: 210, reason: "Cancellation", outcome: "Approved" },
      { date: "2026-01-14", experience: "Skydiving Arizona", amount: 300, reason: "Cancellation", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-004",
    customerId: "CUST-8830",
    customerName: "Aisha Johnson",
    customerEmail: "aisha.j@yahoo.com",
    bookingId: "BK-445781",
    experienceName: "Museum of Modern Art — Private Tour",
    experienceCategory: "Culture",
    experienceValue: 120,
    experienceValuePercentile: 62,
    refundReason: "technical_issue",
    refundAmount: 120,
    refundTimingHours: -5,
    customerTenureMonths: 6,
    refundCountLast6Months: 3,
    totalRefundCount: 4,
    emailEngagement: "opened",
    systemLoginsLast24h: 3,
    previousNoShowCount: 1,
    requestDate: "2026-03-02T11:00:00Z",
    experienceDate: "2026-03-02T06:00:00Z",
    emailEngagementLog: [
      { timestamp: "2026-03-02T05:50:00Z", event: "Email Opened", device: "MacBook Pro", location: "Chicago, IL" },
      { timestamp: "2026-03-02T05:52:00Z", event: "QR Code Generated", device: "MacBook Pro", location: "Chicago, IL" },
    ],
    refundHistory: [
      { date: "2026-01-20", experience: "Jazz Night at the Green Mill", amount: 55, reason: "Technical Issue", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-005",
    customerId: "CUST-5544",
    customerName: "Robert Nguyen",
    customerEmail: "rob.nguyen@protonmail.com",
    bookingId: "BK-219870",
    experienceName: "Broadway — Hamilton (Front Orchestra)",
    experienceCategory: "Entertainment",
    experienceValue: 380,
    experienceValuePercentile: 94,
    refundReason: "cancellation",
    refundAmount: 380,
    refundTimingHours: 10,
    customerTenureMonths: 2,
    refundCountLast6Months: 5,
    totalRefundCount: 6,
    emailEngagement: "opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-01T16:00:00Z",
    experienceDate: "2026-03-02T02:00:00Z",
    refundHistory: [
      { date: "2026-02-20", experience: "Boat Tour — Statue of Liberty", amount: 65, reason: "Cancellation", outcome: "Approved" },
      { date: "2026-02-10", experience: "Rooftop Bar Experience", amount: 75, reason: "Cancellation", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-006",
    customerId: "CUST-1127",
    customerName: "Elena Vasquez",
    customerEmail: "elena.v@gmail.com",
    bookingId: "BK-556612",
    experienceName: "Central Park Bike Tour",
    experienceCategory: "Outdoor",
    experienceValue: 45,
    experienceValuePercentile: 20,
    refundReason: "weather",
    refundAmount: 45,
    refundTimingHours: 120,
    customerTenureMonths: 48,
    refundCountLast6Months: 0,
    totalRefundCount: 1,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T10:00:00Z",
    experienceDate: "2026-03-07T09:00:00Z",
    refundHistory: [],
  }),

  makeCase({
    id: "RC-007",
    customerId: "CUST-6603",
    customerName: "James Wu",
    customerEmail: "jwu@techcorp.io",
    bookingId: "BK-774455",
    experienceName: "Napa Valley Wine Tasting Tour",
    experienceCategory: "Dining",
    experienceValue: 260,
    experienceValuePercentile: 88,
    refundReason: "no_show",
    refundAmount: 260,
    refundTimingHours: -3,
    customerTenureMonths: 18,
    refundCountLast6Months: 14,
    totalRefundCount: 16,
    emailEngagement: "opened",
    systemLoginsLast24h: 1,
    previousNoShowCount: 4,
    requestDate: "2026-03-02T07:45:00Z",
    experienceDate: "2026-03-01T10:00:00Z",
    emailEngagementLog: [
      { timestamp: "2026-03-01T09:30:00Z", event: "Email Opened", device: "Samsung Galaxy", location: "San Francisco, CA" },
      { timestamp: "2026-03-01T09:35:00Z", event: "Voucher Viewed", device: "Samsung Galaxy", location: "San Francisco, CA" },
    ],
    refundHistory: [
      { date: "2026-02-22", experience: "Whale Watching Tour", amount: 120, reason: "No Show", outcome: "Approved" },
      { date: "2026-02-08", experience: "Alcatraz Night Tour", amount: 85, reason: "No Show", outcome: "Approved" },
      { date: "2026-01-18", experience: "Golden Gate Cruise", amount: 70, reason: "No Show", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-008",
    customerId: "CUST-3391",
    customerName: "Fatima Al-Hassan",
    customerEmail: "fatima.ah@email.ae",
    bookingId: "BK-883390",
    experienceName: "Times Square New Year's Experience",
    experienceCategory: "Entertainment",
    experienceValue: 195,
    experienceValuePercentile: 78,
    refundReason: "cancellation",
    refundAmount: 195,
    refundTimingHours: 168,
    customerTenureMonths: 60,
    refundCountLast6Months: 1,
    totalRefundCount: 2,
    emailEngagement: "unavailable",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T13:00:00Z",
    experienceDate: "2026-03-09T20:00:00Z",
    refundHistory: [
      { date: "2024-08-14", experience: "NYC Food Tour", amount: 95, reason: "Cancellation", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-009",
    customerId: "CUST-9912",
    customerName: "Daniel Kim",
    customerEmail: "dkim_88@hotmail.com",
    bookingId: "BK-002211",
    experienceName: "Escape Room Challenge — 5-Person Group",
    experienceCategory: "Entertainment",
    experienceValue: 75,
    experienceValuePercentile: 35,
    refundReason: "technical_issue",
    refundAmount: 75,
    refundTimingHours: -1,
    customerTenureMonths: 3,
    refundCountLast6Months: 4,
    totalRefundCount: 5,
    emailEngagement: "opened",
    systemLoginsLast24h: 2,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T12:30:00Z",
    experienceDate: "2026-03-02T11:30:00Z",
    emailEngagementLog: [
      { timestamp: "2026-03-02T11:15:00Z", event: "Email Opened", device: "Windows PC", location: "Los Angeles, CA" },
    ],
    refundHistory: [
      { date: "2026-02-28", experience: "Art Gallery Tour", amount: 40, reason: "Technical Issue", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-010",
    customerId: "CUST-4456",
    customerName: "Sophie Laurent",
    customerEmail: "sophie.l@paris.fr",
    bookingId: "BK-112398",
    experienceName: "NYC Food and Culture Walking Tour",
    experienceCategory: "Culture",
    experienceValue: 55,
    experienceValuePercentile: 28,
    refundReason: "cancellation",
    refundAmount: 55,
    refundTimingHours: 240,
    customerTenureMonths: 30,
    refundCountLast6Months: 0,
    totalRefundCount: 1,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T09:00:00Z",
    experienceDate: "2026-03-12T10:00:00Z",
    refundHistory: [],
  }),

  makeCase({
    id: "RC-011",
    customerId: "CUST-7741",
    customerName: "Ahmed Patel",
    customerEmail: "ahmed.patel@corp.com",
    bookingId: "BK-556903",
    experienceName: "Private Yacht Charter — Hudson River",
    experienceCategory: "Luxury",
    experienceValue: 1200,
    experienceValuePercentile: 99,
    refundReason: "cancellation",
    refundAmount: 1200,
    refundTimingHours: 18,
    customerTenureMonths: 22,
    refundCountLast6Months: 9,
    totalRefundCount: 11,
    emailEngagement: "opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 1,
    requestDate: "2026-03-02T06:00:00Z",
    experienceDate: "2026-03-03T00:00:00Z",
    refundHistory: [
      { date: "2026-02-14", experience: "Valentine's Rooftop Dinner", amount: 380, reason: "Cancellation", outcome: "Approved" },
      { date: "2026-01-01", experience: "New Year's Luxury Cruise", amount: 850, reason: "Cancellation", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-012",
    customerId: "CUST-2280",
    customerName: "Maria Santos",
    customerEmail: "msantos@gmail.com",
    bookingId: "BK-778891",
    experienceName: "Brooklyn Street Art Tour",
    experienceCategory: "Culture",
    experienceValue: 38,
    experienceValuePercentile: 15,
    refundReason: "weather",
    refundAmount: 38,
    refundTimingHours: 48,
    customerTenureMonths: 24,
    refundCountLast6Months: 1,
    totalRefundCount: 2,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T14:00:00Z",
    experienceDate: "2026-03-04T11:00:00Z",
    refundHistory: [
      { date: "2025-07-20", experience: "Central Park Picnic", amount: 30, reason: "Weather", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-013",
    customerId: "CUST-6617",
    customerName: "Kevin Okafor",
    customerEmail: "kokafor@proton.me",
    bookingId: "BK-001229",
    experienceName: "Comedy Show at Comedy Cellar — Premium Seats",
    experienceCategory: "Entertainment",
    experienceValue: 85,
    experienceValuePercentile: 42,
    refundReason: "no_show",
    refundAmount: 85,
    refundTimingHours: -4,
    customerTenureMonths: 5,
    refundCountLast6Months: 3,
    totalRefundCount: 4,
    emailEngagement: "unavailable",
    systemLoginsLast24h: 0,
    previousNoShowCount: 1,
    requestDate: "2026-03-02T10:30:00Z",
    experienceDate: "2026-03-02T06:30:00Z",
    refundHistory: [
      { date: "2026-02-05", experience: "Improv Comedy Night", amount: 55, reason: "No Show", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-014",
    customerId: "CUST-5519",
    customerName: "Lena Hoffman",
    customerEmail: "lena.hoffman@berlin.de",
    bookingId: "BK-334412",
    experienceName: "Top of the Rock Observation — Sunset Package",
    experienceCategory: "Sightseeing",
    experienceValue: 145,
    experienceValuePercentile: 67,
    refundReason: "cancellation",
    refundAmount: 145,
    refundTimingHours: 96,
    customerTenureMonths: 42,
    refundCountLast6Months: 2,
    totalRefundCount: 2,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T11:15:00Z",
    experienceDate: "2026-03-06T18:00:00Z",
    refundHistory: [
      { date: "2025-09-10", experience: "Empire State Day Tour", amount: 55, reason: "Cancellation", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-015",
    customerId: "CUST-8803",
    customerName: "Raj Malhotra",
    customerEmail: "raj.m@icloud.com",
    bookingId: "BK-990033",
    experienceName: "Private Cooking Class — Michelin Chef",
    experienceCategory: "Dining",
    experienceValue: 490,
    experienceValuePercentile: 97,
    refundReason: "cancellation",
    refundAmount: 490,
    refundTimingHours: 8,
    customerTenureMonths: 11,
    refundCountLast6Months: 13,
    totalRefundCount: 14,
    emailEngagement: "opened",
    systemLoginsLast24h: 1,
    previousNoShowCount: 2,
    requestDate: "2026-03-02T15:00:00Z",
    experienceDate: "2026-03-02T23:00:00Z",
    refundHistory: [
      { date: "2026-02-18", experience: "Sake Tasting Event", amount: 120, reason: "Cancellation", outcome: "Approved" },
      { date: "2026-02-04", experience: "Ramen Making Masterclass", amount: 95, reason: "Cancellation", outcome: "Approved" },
      { date: "2026-01-20", experience: "Chocolate Factory Tour", amount: 65, reason: "Cancellation", outcome: "Denied" },
    ],
  }),

  makeCase({
    id: "RC-016",
    customerId: "CUST-1138",
    customerName: "Chioma Eze",
    customerEmail: "chioma.eze@uni.edu",
    bookingId: "BK-445523",
    experienceName: "Kayaking Brooklyn Bridge",
    experienceCategory: "Outdoor",
    experienceValue: 60,
    experienceValuePercentile: 30,
    refundReason: "cancellation",
    refundAmount: 60,
    refundTimingHours: 200,
    customerTenureMonths: 15,
    refundCountLast6Months: 0,
    totalRefundCount: 0,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T08:00:00Z",
    experienceDate: "2026-03-10T09:00:00Z",
    refundHistory: [],
  }),

  makeCase({
    id: "RC-017",
    customerId: "CUST-4490",
    customerName: "Frank Russo",
    customerEmail: "frank.russo@icloud.com",
    bookingId: "BK-667782",
    experienceName: "Wine & Jazz Evening — Blue Note NYC",
    experienceCategory: "Entertainment",
    experienceValue: 175,
    experienceValuePercentile: 75,
    refundReason: "no_show",
    refundAmount: 175,
    refundTimingHours: -6,
    customerTenureMonths: 9,
    refundCountLast6Months: 18,
    totalRefundCount: 21,
    emailEngagement: "opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 6,
    requestDate: "2026-03-02T13:30:00Z",
    experienceDate: "2026-03-02T07:30:00Z",
    emailEngagementLog: [
      { timestamp: "2026-03-02T07:10:00Z", event: "Email Opened", device: "iPad", location: "Brooklyn, NY" },
      { timestamp: "2026-03-02T07:12:00Z", event: "Event Link Clicked", device: "iPad", location: "Brooklyn, NY" },
    ],
    refundHistory: [
      { date: "2026-02-25", experience: "Stand-Up at MSG", amount: 95, reason: "No Show", outcome: "Approved" },
      { date: "2026-02-11", experience: "Opera at Lincoln Center", amount: 220, reason: "No Show", outcome: "Approved" },
      { date: "2026-01-30", experience: "Late Night Jazz Club", amount: 80, reason: "No Show", outcome: "Denied" },
      { date: "2026-01-09", experience: "Broadway Wicked VIP", amount: 350, reason: "No Show", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-018",
    customerId: "CUST-3312",
    customerName: "Yuki Tanaka",
    customerEmail: "yuki.t@softbank.jp",
    bookingId: "BK-221144",
    experienceName: "Metropolitan Museum — Curator's Private Tour",
    experienceCategory: "Culture",
    experienceValue: 200,
    experienceValuePercentile: 80,
    refundReason: "cancellation",
    refundAmount: 200,
    refundTimingHours: 336,
    customerTenureMonths: 55,
    refundCountLast6Months: 0,
    totalRefundCount: 1,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T12:00:00Z",
    experienceDate: "2026-03-16T14:00:00Z",
    refundHistory: [],
  }),

  makeCase({
    id: "RC-019",
    customerId: "CUST-7760",
    customerName: "Carlos Mendez",
    customerEmail: "carlos.m@outlook.com",
    bookingId: "BK-889901",
    experienceName: "Rock Climbing — Indoor Extreme Course",
    experienceCategory: "Adventure",
    experienceValue: 65,
    experienceValuePercentile: 33,
    refundReason: "technical_issue",
    refundAmount: 65,
    refundTimingHours: -2,
    customerTenureMonths: 7,
    refundCountLast6Months: 6,
    totalRefundCount: 7,
    emailEngagement: "opened",
    systemLoginsLast24h: 4,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T09:45:00Z",
    experienceDate: "2026-03-02T07:45:00Z",
    emailEngagementLog: [
      { timestamp: "2026-03-02T07:30:00Z", event: "Email Opened", device: "Android Phone", location: "Miami, FL" },
      { timestamp: "2026-03-02T07:33:00Z", event: "Digital Ticket Accessed", device: "Android Phone", location: "Miami, FL" },
    ],
    refundHistory: [
      { date: "2026-02-20", experience: "Surf Lesson", amount: 55, reason: "Technical Issue", outcome: "Approved" },
      { date: "2026-02-01", experience: "ATV Tour", amount: 150, reason: "Technical Issue", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-020",
    customerId: "CUST-2245",
    customerName: "Isabelle Dupont",
    customerEmail: "isa.dupont@sfr.fr",
    bookingId: "BK-334987",
    experienceName: "High Line Guided Art Walk",
    experienceCategory: "Culture",
    experienceValue: 42,
    experienceValuePercentile: 18,
    refundReason: "cancellation",
    refundAmount: 42,
    refundTimingHours: 180,
    customerTenureMonths: 31,
    refundCountLast6Months: 2,
    totalRefundCount: 2,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T10:20:00Z",
    experienceDate: "2026-03-09T11:00:00Z",
    refundHistory: [
      { date: "2025-10-18", experience: "Chelsea Market Culinary Tour", amount: 70, reason: "Cancellation", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-021",
    customerId: "CUST-9955",
    customerName: "Brian Wallace",
    customerEmail: "bwallace@corp.us",
    bookingId: "BK-112784",
    experienceName: "Luxury Spa & Wellness Day — The Plaza",
    experienceCategory: "Luxury",
    experienceValue: 350,
    experienceValuePercentile: 93,
    refundReason: "cancellation",
    refundAmount: 350,
    refundTimingHours: 20,
    customerTenureMonths: 4,
    refundCountLast6Months: 8,
    totalRefundCount: 9,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T11:45:00Z",
    experienceDate: "2026-03-03T07:45:00Z",
    refundHistory: [
      { date: "2026-02-18", experience: "Yoga Retreat Weekend", amount: 200, reason: "Cancellation", outcome: "Approved" },
      { date: "2026-02-02", experience: "Sound Bath Session", amount: 80, reason: "Cancellation", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-022",
    customerId: "CUST-4478",
    customerName: "Nadia Kowalski",
    customerEmail: "nadia.k@wp.pl",
    bookingId: "BK-556234",
    experienceName: "East Village Ghost Tour",
    experienceCategory: "Entertainment",
    experienceValue: 35,
    experienceValuePercentile: 12,
    refundReason: "cancellation",
    refundAmount: 35,
    refundTimingHours: 120,
    customerTenureMonths: 27,
    refundCountLast6Months: 1,
    totalRefundCount: 1,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T15:30:00Z",
    experienceDate: "2026-03-07T22:00:00Z",
    refundHistory: [],
  }),

  makeCase({
    id: "RC-023",
    customerId: "CUST-7723",
    customerName: "Omar Abdullah",
    customerEmail: "o.abdullah@dubai.ae",
    bookingId: "BK-778234",
    experienceName: "Private Helicopter — NYC Night Tour",
    experienceCategory: "Luxury",
    experienceValue: 1800,
    experienceValuePercentile: 99,
    refundReason: "cancellation",
    refundAmount: 1800,
    refundTimingHours: 12,
    customerTenureMonths: 7,
    refundCountLast6Months: 11,
    totalRefundCount: 13,
    emailEngagement: "opened",
    systemLoginsLast24h: 1,
    previousNoShowCount: 2,
    requestDate: "2026-03-02T08:15:00Z",
    experienceDate: "2026-03-02T20:15:00Z",
    refundHistory: [
      { date: "2026-02-25", experience: "Private Yacht — Sunset", amount: 1200, reason: "Cancellation", outcome: "Approved" },
      { date: "2026-02-10", experience: "Helicopter Niagara Falls", amount: 900, reason: "Cancellation", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-024",
    customerId: "CUST-6681",
    customerName: "Sarah Mitchell",
    customerEmail: "sarah.m@gmail.com",
    bookingId: "BK-991567",
    experienceName: "NYC Photography Workshop",
    experienceCategory: "Culture",
    experienceValue: 95,
    experienceValuePercentile: 50,
    refundReason: "other",
    refundAmount: 95,
    refundTimingHours: 336,
    customerTenureMonths: 38,
    refundCountLast6Months: 1,
    totalRefundCount: 3,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T14:30:00Z",
    experienceDate: "2026-03-16T09:00:00Z",
    refundHistory: [
      { date: "2025-11-15", experience: "Film Photography Class", amount: 85, reason: "Scheduling Conflict", outcome: "Approved" },
    ],
  }),

  makeCase({
    id: "RC-025",
    customerId: "CUST-3389",
    customerName: "Leo Fischer",
    customerEmail: "leo.f@gmx.de",
    bookingId: "BK-004512",
    experienceName: "Brooklyn Brewery Tour & Tasting",
    experienceCategory: "Dining",
    experienceValue: 48,
    experienceValuePercentile: 22,
    refundReason: "cancellation",
    refundAmount: 48,
    refundTimingHours: 72,
    customerTenureMonths: 0,
    refundCountLast6Months: 4,
    totalRefundCount: 4,
    emailEngagement: "not_opened",
    systemLoginsLast24h: 0,
    previousNoShowCount: 0,
    requestDate: "2026-03-02T13:00:00Z",
    experienceDate: "2026-03-05T15:00:00Z",
    refundHistory: [
      { date: "2026-02-28", experience: "Rooftop Bar Hop", amount: 75, reason: "Cancellation", outcome: "Approved" },
      { date: "2026-02-25", experience: "Craft Cocktail Class", amount: 90, reason: "Cancellation", outcome: "Approved" },
      { date: "2026-02-20", experience: "Wine Pairing Dinner", amount: 130, reason: "Cancellation", outcome: "Approved" },
    ],
  }),
];

export function getCaseById(id: string): RefundCase | undefined {
  return MOCK_CASES.find((c) => c.id === id);
}

export function getDashboardMetrics() {
  const total = MOCK_CASES.length;
  const autoApproved = MOCK_CASES.filter((c) => c.status === "auto_approved").length;
  const mediumRisk = MOCK_CASES.filter((c) => c.status === "medium_risk").length;
  const highRisk = MOCK_CASES.filter((c) => c.status === "high_risk").length;
  const avgScore = Math.round(MOCK_CASES.reduce((acc, c) => acc + (c.riskAssessment?.totalScore || 0), 0) / total);

  return {
    totalCases: total,
    autoApproved,
    mediumRisk,
    highRisk,
    approved: 0,
    denied: 0,
    escalated: 0,
    avgRiskScore: avgScore,
    manualReviewHoursTarget: 375,
    manualReviewHoursCurrent: Math.round((mediumRisk + highRisk) * 5 / 60 * 100),
    fraudReductionPct: 62,
    falsePosRate: 3.2,
    autoApprovalRate: Math.round((autoApproved / total) * 100),
  };
}
